/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DeviceInfo {
  vendor: string
  model: string
  serial: string
  firmware: string
  imageWidth: number
  imageHeight: number
  dpi: number
}
export interface ScanResult {
  image: Array<number>
  quality: number
  template: Array<number>
  timestamp: number
}
export interface MatchResult {
  matched: boolean
  score: number
  userId?: string
}
export interface Template {
  userId: string
  data: Array<number>
  createdAt: number
}
export interface CaptureOptions {
  timeoutMs?: number
  minQuality?: number
  autoCapture?: boolean
}
export const enum ScannerStatus {
  Connected = 'Connected',
  Disconnected = 'Disconnected',
  Capturing = 'Capturing',
  Error = 'Error'
}
export interface ScannerStatusInfo {
  status: string
  vendor?: string
  model?: string
}
export interface UpdateInfo {
  updateAvailable: boolean
  currentVersion: string
  latestVersion?: string
  releaseUrl?: string
}
export declare function checkForUpdate(): Promise<UpdateInfo>
export declare function initScanner(vendor?: string | undefined | null): Promise<DeviceInfo>
export declare function captureFingerprint(options?: CaptureOptions | undefined | null): Promise<ScanResult>
export declare function enrollUser(userId: string, samples?: number | undefined | null): Promise<Template>
export declare function verifyUser(userId: string, template: Template): Promise<MatchResult>
export declare function identifyUser(templates: Array<Template>): Promise<MatchResult>
export declare function disconnectScanner(): Promise<void>
export declare function getScannerStatus(): Promise<ScannerStatusInfo>
